In [8]:
#Příprava dat do košíků - Vytvoření pole košíků
import pyreadstat
df, meta = pyreadstat.read_sav('Shopping_items.sav')  #Načte .sav file
kosikID = 1
kosiky = []
kosik = []
for row in df.values:
    if kosikID != row[0]: 
        kosikID = row[0]
        kosiky.append(kosik)
        kosik = []
    kosik.append(row[1])
print("Příklad přvních tří košíků \n", kosiky[0],"\n", kosiky[1],"\n", kosiky [2])

Příklad přvních tří košíků
 ['READMADE', 'SNACKS']
 ['READMADE', 'TOILETRY']
 ['READMADE', 'TOILETRY', 'SNACKS']

In [17]:
#Převod pole košíků do DataFrame příznaků
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_array = te.fit(kosiky).transform(kosiky)
df = pd.DataFrame(te_array, columns = te.columns_)
df

,ALCOHOL,BAKERY,FROZEN,MEAT,MILK,READMADE,SNACKS,TINNED,TOILETRY,VEG
0,False,False,False,False,False,True,True,False,False,False
1,False,False,False,False,False,True,False,False,True,False
2,False,False,False,False,False,True,True,False,True,False
3,False,True,False,False,True,True,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
780,True,False,True,False,False,False,False,True,True,False
781,True,False,False,False,False,False,False,False,False,False
782,False,True,True,False,False,True,True,False,False,False
783,True,False,False,False,False,False,False,False,False,False
784,True,False,True,False,False,False,True,False,False,False

In [20]:
#Gereování frekventovaných množin pomocí apriori algoritmu
from mlxtend.frequent_patterns import apriori
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)
frequent_itemsets

     support                             itemsets
0   0.394904                            (ALCOHOL)
1   0.429299                             (BAKERY)
2   0.401274                             (FROZEN)
3   0.188535                               (MILK)
4   0.492994                           (READMADE)
5   0.475159                             (SNACKS)
6   0.456051                             (TINNED)
7   0.215287                    (BAKERY, ALCOHOL)
8   0.230573                    (FROZEN, ALCOHOL)
9   0.114650                      (MILK, ALCOHOL)
10  0.212739                  (READMADE, ALCOHOL)
11  0.219108                    (SNACKS, ALCOHOL)
12  0.173248                    (TINNED, ALCOHOL)
13  0.221656                     (BAKERY, FROZEN)
14  0.140127                       (BAKERY, MILK)
15  0.256051                   (READMADE, BAKERY)
16  0.233121                     (BAKERY, SNACKS)
17  0.228025                     (TINNED, BAKERY)
18  0.108280                       (MILK, FROZEN)
19  0.211465                   (READMADE, FROZEN)
20  0.214013                     (SNACKS, FROZEN)
21  0.207643                     (TINNED, FROZEN)
22  0.133758                     (READMADE, MILK)
23  0.124841                       (SNACKS, MILK)
24  0.127389                       (TINNED, MILK)
25  0.244586                   (READMADE, SNACKS)
26  0.216561                   (TINNED, READMADE)
27  0.224204                     (TINNED, SNACKS)
28  0.142675            (BAKERY, FROZEN, ALCOHOL)
29  0.146497          (READMADE, BAKERY, ALCOHOL)
30  0.137580            (BAKERY, SNACKS, ALCOHOL)
31  0.123567            (TINNED, BAKERY, ALCOHOL)
32  0.143949          (READMADE, FROZEN, ALCOHOL)
33  0.142675            (SNACKS, FROZEN, ALCOHOL)
34  0.121019            (TINNED, FROZEN, ALCOHOL)
35  0.135032          (READMADE, SNACKS, ALCOHOL)
36  0.121019          (TINNED, READMADE, ALCOHOL)
37  0.115924            (TINNED, SNACKS, ALCOHOL)
38  0.138854           (READMADE, BAKERY, FROZEN)
39  0.136306             (BAKERY, SNACKS, FROZEN)
40  0.149045             (TINNED, BAKERY, FROZEN)
41  0.105732             (READMADE, BAKERY, MILK)
42  0.100637               (TINNED, BAKERY, MILK)
43  0.147771           (READMADE, BAKERY, SNACKS)
44  0.146497           (TINNED, READMADE, BAKERY)
45  0.137580             (TINNED, BAKERY, SNACKS)
46  0.127389           (READMADE, SNACKS, FROZEN)
47  0.126115           (TINNED, READMADE, FROZEN)
48  0.114650             (TINNED, SNACKS, FROZEN)
49  0.138854           (TINNED, READMADE, SNACKS)
50  0.104459  (READMADE, BAKERY, FROZEN, ALCOHOL)
51  0.101911  (READMADE, BAKERY, SNACKS, ALCOHOL)
52  0.100637  (TINNED, READMADE, BAKERY, ALCOHOL)

In [26]:
#Vytvoření asociačních pravidel
from mlxtend.frequent_patterns import association_rules
res = association_rules(frequent_itemsets, metric="confidence",min_threshold=0.5)
res.sort_values(by=['confidence'])

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
13,(TINNED),(BAKERY),0.456051,0.429299,0.228025,0.500000,1.164688,0.032243,1.141401
0,(BAKERY),(ALCOHOL),0.429299,0.394904,0.215287,0.501484,1.269886,0.045754,1.213793
83,"(TINNED, SNACKS)",(FROZEN),0.224204,0.401274,0.114650,0.511364,1.274351,0.024683,1.225300
22,(SNACKS),(READMADE),0.475159,0.492994,0.244586,0.514745,1.044122,0.010336,1.044825
7,(BAKERY),(FROZEN),0.429299,0.401274,0.221656,0.516320,1.286703,0.049389,1.237857
...,...,...,...,...,...,...,...,...,...
95,"(READMADE, SNACKS, ALCOHOL)",(BAKERY),0.135032,0.429299,0.101911,0.754717,1.758020,0.043942,2.326703
65,"(TINNED, MILK)",(BAKERY),0.127389,0.429299,0.100637,0.790000,1.840208,0.045949,2.717622
62,"(READMADE, MILK)",(BAKERY),0.133758,0.429299,0.105732,0.790476,1.841317,0.048310,2.723798
99,"(TINNED, BAKERY, ALCOHOL)",(READMADE),0.123567,0.492994,0.100637,0.814433,1.652015,0.039719,2.732201
98,"(TINNED, READMADE, ALCOHOL)",(BAKERY),0.121019,0.429299,0.100637,0.831579,1.937061,0.048684,3.388535